[package]
name = "eid_mls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eid_traits = { version = "0.1.0", path = "../traits" }
openmls = { git = "https://github.com/openmls/openmls.git" }
openmls_rust_crypto = { git = "https://github.com/openmls/openmls.git" }
thiserror = "1.0"
mls-assist = { git = "https://github.com/phnx-im/mls-assist-student.git", rev = "750fd3d3784fb39611ad6343a6f66ca8dc160932" }
tls_codec = "0.2.0"

[features]
test = ["openmls/test-utils"]
