[package]
name = "eid_mls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eid_traits = { version = "0.1.0", path = "../traits" }
openmls = "0.4.1"
openmls_rust_crypto = "0.1.0"
